# Generated by Django 4.2.26 on 2025-11-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(default='fa-solid fa-pen-fancy', help_text='CSS class for the icon', max_length=100),
        ),
    ]
